"""create new db file

Revision ID: e02de69a4e2d
Revises: 
Create Date: 2020-04-29 22:24:08.837706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02de69a4e2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amo_login', sa.String(length=100), nullable=True),
    sa.Column('amo_hash', sa.String(length=40), nullable=True),
    sa.Column('amo_url', sa.String(length=100), nullable=False),
    sa.Column('ms_auth', sa.String(length=72), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amo_url')
    )
    op.create_index(op.f('ix_account_amo_login'), 'account', ['amo_login'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amo_field_id', sa.Integer(), nullable=True),
    sa.Column('ms_field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amo_status_id', sa.Integer(), nullable=True),
    sa.Column('ms_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_status')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_account_amo_login'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
